### ISSUE TITLE
Review Project Plan

### ISSUE THREAD

**Issue by irem-uguz** [bounswe/bounswe2019group9#122]

**Comment by corupta** [comment]
Proof Reading & Revising Project Plan

**Comment by corupta** [comment]
It seems that
after [project plan version 3](https://github.com/bounswe/bounswe2019group9/blob/eba4b85a4635c229adfd2d7497efb672aab59ff2/deliverables/Project_Plan/project_plan_g9.pdf)

2 differen next versions (A)[https://github.com/bounswe/bounswe2019group9/blob/master/deliverables/Project_Plan/project_plan_g9.pdf] and (B)[https://github.com/bounswe/bounswe2019group9/blob/master/deliverables/Project_Plan/ProjectPlan.pdf] were created, each of them fixing some problems of the version 3 as well as both adding some new entries (tasks).

Also, both of these versions' PDF are exported in a way that resources cannot be seen whereas version 3's PDF includes resources. Other than that, there are some typos in task names in the plan such as milestone => milistone 

The two project plan will be merged into one.

**Comment by corupta** [comment]
Done, for use in future here's a useful tip about project libre, to edit the size of pdf do not click export to pdf but instead `preview`. Then, in the preview screen, at the top right combobox `Printers`, select `ProjectLibre PDF`. Now, you can change margins, which diagrams to include, and the most important `scaling`

However, the export mechanism is designed so that each row in the spreadsheet table is next to a row in the gantt chart. To ensure that it tries to print 7 pages wide x 3 pages high for example. So, for printing measures it makes sense, You get 21 pages (papers) and if you align them as a grid in the physical world, they'd form a big chart where you can see the whole plan as one.

Yet, when exporting for digital viewing, such mechanism is horrendous. Thus, I've exported spreadsheet and Gannt chart separately making spreadsheet part 1 pages wide x 3 pages high and chart part 3 pages wide x 1 pages high, and then merged the two pdfs together. 

A better approach for exporting for digital use would be to scale the whole thing down such that it would fit in 1 page wide x 1 page high and export it as 1 page pdf. Since the pdf is not just a jpeg/pixelated image and encodes fonts inside as fonts and vectors as vectors there's no resolution loss even if you scale down to 5%. That way the user viewing the pdf can zoom as much as he/she wants while seeing the whole thing as one.

I'm writing this that detailed, as I believe it may be very useful in the future.
